global:
  scrape_interval: 15s

scrape_configs:
  - job_name: backend
    metrics_path: /metrics
    static_configs:
      - targets:
          - backend:3000
          - host.docker.internal:3000

  - job_name: otel-collector
    static_configs:
      - targets:
          - otel-collector:8888
